[versions]

core = "1.13.1"
appcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.1.4"
activity = "1.9.2"

android = "8.6.0"
kotlin = "2.0.20"

sdk-min = "26"
sdk-compile = "34"
sdk-target = "34"
java-target = "17"

[libraries]

core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }

[plugins]

android = { id = "com.android.application", version.ref = "android" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }